-- =============================================================================
-- schema.sql
-- BigQuery DDL for the user_events table.
--
-- Usage:
--   bq query --use_legacy_sql=false < bq/schema.sql
--   OR paste into the BigQuery console.
--
-- Notes:
--   • The table is partitioned by DAY on the `timestamp` column so that
--     queries filtering on a date range only scan the relevant partitions
--     (cost savings + performance).
--   • A clustering key on (event, product) further prunes data for the
--     most common analytical query patterns.
--   • Partition expiry is set to 365 days to avoid unbounded storage costs.
--     Remove or adjust `partition_expiration_days` for production retention
--     requirements.
-- =============================================================================

-- Create the dataset (run once per environment) ---------------------------------
-- Replace `my_gcp_project` and `analytics` with your actual project / dataset.
-- CREATE SCHEMA IF NOT EXISTS `my_gcp_project.analytics`
-- OPTIONS (
--     location = 'US'
-- );

-- =============================================================================
-- Main events table
-- =============================================================================
CREATE TABLE IF NOT EXISTS `my_gcp_project.analytics.user_events`
(
    -- Unique identifier for every event (UUID v4 from the producer)
    event_id         STRING    NOT NULL,

    -- Simulated user identifier
    user_id          INT64     NOT NULL,

    -- Activity type: click | view | purchase
    event            STRING    NOT NULL,

    -- Product involved: laptop | phone | shoes | headphones | tablet | watch
    product          STRING    NOT NULL,

    -- Product price in USD at time of event
    price            FLOAT64   NOT NULL,

    -- Event timestamp as generated by the producer (UTC)
    -- Used as the partition column — MUST be TIMESTAMP type for date partitioning
    `timestamp`      TIMESTAMP NOT NULL,

    -- Timestamp when the record was written to BigQuery by the Dataflow pipeline
    ingestion_ts     TIMESTAMP NOT NULL,

    -- Version of the pipeline that processed this record (useful for debugging)
    pipeline_version STRING
)
PARTITION BY DATE(`timestamp`)    -- daily partitions → cheaper, faster range queries
CLUSTER BY event, product         -- further prune data for common query patterns
OPTIONS (
    -- Automatically delete partitions older than 365 days.
    -- Adjust or remove this for your retention requirements.
    partition_expiration_days = 365,
    description = "User activity events (click / view / purchase) ingested via the GCP streaming pipeline."
);

-- =============================================================================
-- Useful views
-- =============================================================================

-- Daily event summary --------------------------------------------------------
CREATE OR REPLACE VIEW `my_gcp_project.analytics.vw_daily_event_summary` AS
SELECT
    DATE(`timestamp`)    AS event_date,
    event,
    product,
    COUNT(*)             AS event_count,
    ROUND(SUM(price), 2) AS total_revenue,
    ROUND(AVG(price), 2) AS avg_price
FROM `my_gcp_project.analytics.user_events`
GROUP BY 1, 2, 3
ORDER BY 1 DESC, event_count DESC;


-- Unique active users per day -------------------------------------------------
CREATE OR REPLACE VIEW `my_gcp_project.analytics.vw_daily_active_users` AS
SELECT
    DATE(`timestamp`)    AS event_date,
    COUNT(DISTINCT user_id) AS active_users
FROM `my_gcp_project.analytics.user_events`
GROUP BY 1
ORDER BY 1 DESC;


-- Purchase funnel (click → view → purchase per product) ----------------------
CREATE OR REPLACE VIEW `my_gcp_project.analytics.vw_purchase_funnel` AS
SELECT
    product,
    COUNTIF(event = 'click')    AS clicks,
    COUNTIF(event = 'view')     AS views,
    COUNTIF(event = 'purchase') AS purchases,
    ROUND(
        SAFE_DIVIDE(COUNTIF(event = 'purchase'), COUNTIF(event = 'click')) * 100, 2
    ) AS purchase_rate_pct
FROM `my_gcp_project.analytics.user_events`
GROUP BY product
ORDER BY purchases DESC;

